name: LoiTPH first Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Check out repository
      uses: actions/checkout@v3

    - name: 2. Use Node.js 20
      uses: action/setup-node@v3
      with:
        node-version: 20

    - name: 3. Print a message
      run: echo "Yoooo Loi!"